project_id = "dvomgnudbwkdcavihebw"

[functions.scan-receipt]
verify_jwt = false

[functions.parse-voice]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.get-stock-price]
verify_jwt = false

[functions.ai-copilot]
verify_jwt = false
